

package dpproject;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.SwingUtilities;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;

/**
 *
 * @author misge
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     *  
     */
    //List<Employee> employees = new ArrayList<Employee>();
    private JTree tree;
    //private JLabel selectedLabel;
    public GUI() {
            DefaultMutableTreeNode root = new DefaultMutableTreeNode("CEO");
        //create the child nodes
        DefaultMutableTreeNode MktVp = new DefaultMutableTreeNode("MktVP");
        DefaultMutableTreeNode SalMgr = new DefaultMutableTreeNode("SalMgr");
        SalMgr.add(new DefaultMutableTreeNode("sales1"));
        SalMgr.add(new DefaultMutableTreeNode("sales2"));
        DefaultMutableTreeNode MktMgr = new DefaultMutableTreeNode("MktMgr");
        MktMgr.add(new DefaultMutableTreeNode("Sacy1"));
        MktMgr.add(new DefaultMutableTreeNode("Sacy2"));
        DefaultMutableTreeNode ProdVp  = new DefaultMutableTreeNode("ProdVP");
        ProdVp.add(new DefaultMutableTreeNode("prodMgr"));
        ProdVp.add(new DefaultMutableTreeNode("shipMgr"));
        DefaultMutableTreeNode ProdMgr = new DefaultMutableTreeNode("ProdMgr");
        ProdMgr.add(new DefaultMutableTreeNode("Menu1"));
        ProdMgr.add(new DefaultMutableTreeNode("Menu2"));
        ProdMgr.add(new DefaultMutableTreeNode("Menu3"));
        DefaultMutableTreeNode ShipMgr = new DefaultMutableTreeNode("ShipMgr");
        ShipMgr.add(new DefaultMutableTreeNode("Ship1"));
        ShipMgr.add(new DefaultMutableTreeNode("Ship2"));
         
        //add the child nodes to the root node
        MktVp.add(SalMgr);
        MktVp.add( MktMgr);
        ProdVp.add(ShipMgr);
        ProdVp.add(ProdMgr);
        root.add(MktVp);
        root.add(ProdVp);
        //create the tree by passing in the root node
        tree = new JTree(root);
        // tree.setCellRenderer(renderer);
        tree.setShowsRootHandles(true);
        tree.setRootVisible(true);
        add(new JScrollPane(tree));
        
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("Composit Pattern"); 
        this.setLocationRelativeTo(null);
        this.setSize(800, 400);
        this.setVisible(true);
        
        
        initComponents();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
